### ISSUE TITLE
Party Class anlegen

### ISSUE THREAD

**Issue by hientp** [PatDue/WarriorsBattle#1]
Anlage einer Class mittels welcher die individuellen PartY Objekte erzeugt werden. Die einzelnen Parties wiederum bestehen aus einzelnen Character Objekten.

**Comment by PatDue** [comment]
Party Class wurde in Development angelegt. Es können Objekte erzeugt werden (new Party), Character Objekte hinzugefügt (party.addMember(member)) und eine Liste der hinzugefügten Character Objekte angezeigt (party.showMembers(true)) werden.

Offen ist die Abstimmung der enthaltenen Methoden auf die Classe Character und deren Subclasses.
