### ISSUE TITLE
Character Class (Warrior & Wizard) anlegen

### ISSUE THREAD

**Issue by hientp** [PatDue/WarriorsBattle#2]

**Comment by PatDue** [comment]
Hey @hientp könntest du anstatt eines "String partyName" die Zugehörigkeit zu einer Party durch das entsprechende Party Objekt ("private Party party") regeln?
Im Constructor kann dann einfach "party.addMember(this);" aufgerufen werden und der neue Character ist gleich Mitglied der jeweiligen Party.

**Comment by hientp** [comment]
Charakter Klassen sind erstellt.
