### ISSUE TITLE
Auto Objekt Erstellung

### ISSUE THREAD

**Issue by hientp** [PatDue/WarriorsBattle#8]
Create a full party of randomly generated Wizards and Warriors with randomized stats considering these limits.

    name: based on an array of names, pick a random position, and if is already in the party add Jr at the end.
    hp: random between 100-200 to warriors, 50-100 for wizards)
    stamina: random between 10-50
    strength: random between 1-10
    mana: random between 10-50
    intelligence: random between 1-50

**Comment by PatDue** [comment]
Methode zur automatischen Generierung von Characteren und Zuweisung zu einer Party erstellt (party.createRandomMembers()).

Offen ist die Abstimmung mit der Character Class und deren Subclasses.
